import random
NEWS_API_KEY = "e7ebf6d7eecf479e95dcc55b4b5c812b"
NUM_ARTICLES = 5
DEDUPLICATE_NEWS = True 
NEWS_LANGUAGE = "en"

# 📰 NEWS VARIETY
# Categories: technology, business, entertainment, general, health, science, sports
#NEWS_CATEGORIES = [
#    "NVIDIA GPU", "Intel CPU", "AMD Ryzen", "computer gaming news",
#    "information technology", "cloud computing", "AWS Azure Google Cloud",
#    "cybersecurity", "software development", "programming news",
#    "linux open source", "gadgets", "smartphones", "quantum computing",
#    "robotics", "automation", "server hardware", "networking IT"
#]

NEWS_CATEGORIES = [
	"Technology",
	"Information Technology",
	"cloud computing",
	"high performance computing",
	"open source",
	"opensource",
	"Software",
    "Artificial Intelligence",
    "Machine Learning",
    "Generative AI",
    "OpenAI",
    "ChatGPT",
    "LLM Models",
    "AI Automation",
    "AI Startups",
    "AI Coding Tools",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "AI Agents",
    "Neural Networks",
    "Reinforcement Learning",
    "Federated Learning",
    "Transfer Learning",
    "Multimodal AI",
    "Diffusion Models",
    "Transformer Architecture",
    "Claude AI",
    "Gemini AI",
    "Mistral AI",
    "LLaMA",
    "AI Ethics",
    "AI Safety",
    "AI Regulation",
    "AI Hardware",
    "Edge AI",
    "TinyML",
    "Ollama",
    "OpenWebUI",
    "ComfyUI",
    "Stable Diffusion",
    "Flux AI",
    "NVIDIA GPU",
    "Intel CPU",
    "AMD Ryzen",
    "ARM Processors",
    "RISC-V",
    "TSMC",
    "Qualcomm",
    "Apple Silicon",
    "Semiconductor Industry",
    "Chip Manufacturing",
    "Cloud Computing",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "DevOps",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Ansible",
    "OpenStack",
    "VMware",
    "Cybersecurity",
    "Ethical Hacking",
    "Ransomware",
    "Malware Analysis",
    "Data Breaches",
    "Zero Trust Architecture",
    "SOC Security",
    "Network Security",
    "Penetration Testing",
    "Digital Forensics",
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Kotlin",
    "Swift",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Linux",
    "Ubuntu",
    "Debian",
    "Arch Linux",
    "Fedora",
    "Kali Linux",
    "Red Hat",
    "Open Source Software",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Apache Kafka",
    "Apache Hadoop",
    "Apache Spark",
    "Big Data",
    "Data Engineering",
    "Business Intelligence",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Web3",
    "NFT",
    "DeFi",
    "Quantum Computing",
    "Robotics",
    "Humanoid Robots",
    "Space Technology",
    "NASA",
    "ISRO",
    "SpaceX",
    "Starlink",
    "5G Technology",
    "6G Research",
    "Virtual Reality",
    "Augmented Reality",
    "Mixed Reality",
    "Metaverse",
    "Electric Vehicles",
    "Battery Technology",
    "Autonomous Vehicles",
    "Drone Technology",
    "Technology Startups",
    "Venture Capital",
    "IPO Technology",
    "Silicon Valley",
    "Big Tech Companies",
    "Technology Business News",
    "Ubuntu Desktop",
    "Ubuntu Server",
    "Ubuntu Core",
    "Kubuntu",
    "Lubuntu",
    "Xubuntu",
    "Ubuntu MATE",
    "Ubuntu Studio",
    "Edubuntu",
    "Ubuntu Kylin",
    "Pop!_OS",
    "Linux Mint",
    "Fedora Workstation",
    "Fedora Server",
    "Fedora Silverblue",
    "Fedora Kinoite",
    "Red Hat Enterprise Linux",
    "RHEL",
    "CentOS",
    "CentOS Stream",
    "Rocky Linux",
    "AlmaLinux",
    "Oracle Linux",
    "Scientific Linux",
    "Clear Linux",
    "SUSE Linux Enterprise",
    "openSUSE",
    "openSUSE Leap",
    "openSUSE Tumbleweed",
    "Manjaro",
    "EndeavourOS",
    "Garuda Linux",
    "CachyOS",
    "ArcoLinux",
    "Artix Linux",
    "BlackArch Linux",
    "Parabola GNU/Linux",
    "Gentoo",
    "Sabayon Linux",
    "Calculate Linux",
    "Slackware",
    "Puppy Linux",
    "Tiny Core Linux",
    "Bodhi Linux",
    "PCLinuxOS",
    "Peppermint OS",
    "antiX",
    "MX Linux",
    "Zorin OS",
    "elementary OS",
    "Deepin",
    "Nitrux",
    "KaOS",
    "Mageia",
    "OpenMandriva",
    "Solus",
    "Void Linux",
    "NixOS",
    "Guix System",
    "Alpine Linux",
    "Devuan",
    "Raspberry Pi OS",
    "DietPi",
    "Armbian",
    "Parrot OS",
    "BackBox Linux",
    "CAINE",
    "Tails",
    "Qubes OS",
    "Whonix",
    "Kodachi Linux",
    "PureOS",
    "Endless OS",
    "Bazzite",
    "Bluefin Linux",
    "Aurora Linux",
    "Vanilla OS",
    "BlendOS",
    "Nobara Linux",
    "SteamOS",
    "ChromeOS Flex",
    "FydeOS",
    "Android-x86",
    "Phoenix OS",
    "PrimeOS",
    "Remix OS",
    "EasyOS",
    "SparkyLinux",
    "Slax",
    "Linux Lite",
    "OpenWrt",
    "DD-WRT",
    "pfSense",
    "OPNsense",
    "IPFire",
    "FreeBSD",
    "OpenBSD",
    "NetBSD",
    "DragonFly BSD",
    "GhostBSD",
    "MidnightBSD",
    "NomadBSD",
    "HardenedBSD",
    "TrueNAS CORE",
    "TrueNAS SCALE",
    "UNIX",
    "AIX",
    "HP-UX",
    "Solaris",
    "OpenSolaris",
    "Illumos",
    "SmartOS",
    "macOS",
    "macOS Sequoia",
    "macOS Sonoma",
    "macOS Ventura",
    "Mac OS X",
    "iOS",
    "iPadOS",
    "watchOS",
    "tvOS",
    "visionOS",
    "Microsoft Windows",
    "Windows 11",
    "Windows 10",
    "Windows Server",
    "Windows Server 2025",
    "Windows Server 2022",
    "Windows Server 2019",
    "Windows Server 2016",
    "Windows Insider",
    "Windows Subsystem for Linux",
    "WSL",
    "Windows IoT",
    "Android",
    "Android 16",
    "Android 15",
    "Android TV",
    "Wear OS",
    "ChromeOS",
    "Fuchsia OS",
    "HarmonyOS",
    "HarmonyOS NEXT",
    "KaiOS",
    "Sailfish OS",
    "Ubuntu Touch",
    "postmarketOS",
    "Plasma Mobile",
    "PureOS Mobile",
    "Mobian",
    "Embedded Linux",
    "Yocto Project",
    "Buildroot",
    "OpenEmbedded",
    "RIOT OS",
    "TinyOS",
    "Mbed OS",
    "Zephyr RTOS",
    "FreeRTOS",
    "Zephyr",
    "VxWorks",
    "QNX",
    "ThreadX",
    "NuttX",
    "RTEMS",
    "eCos",
    "ChibiOS",
    "Contiki OS",
    "VMware ESXi",
    "VMware vSphere",
    "VMware Workstation",
    "Proxmox VE",
    "XCP-ng",
    "Xen",
    "KVM",
    "QEMU",
    "VirtualBox",
    "Hyper-V",
    "oVirt",
    "Docker Desktop",
    "Podman",
    "containerd",
    "CRI-O",
    "LXC",
    "LXD",
    "systemd-nspawn",
    "TrueNAS",
    "OpenMediaVault",
    "Unraid",
    "Rockstor",
    "XigmaNAS",
    "Tomato Firmware",
    "VyOS",
    "RouterOS",
    "Fedora CoreOS",
    "Red Hat CoreOS",
    "Bottlerocket",
    "Flatcar Container Linux",
    "Talos Linux",
    "RancherOS",
    "MS-DOS",
    "FreeDOS",
    "OS/2",
    "BeOS",
    "Haiku OS",
    "ReactOS",
    "AmigaOS",
    "MorphOS",
    "AROS",
    "TempleOS",
    "IBM z/OS",
    "IBM z/VM",
    "IBM i",
    "OpenVMS",
    "Batocera",
    "Lakka",
    "Recalbox",
    "Rocks Cluster",
    "Warewulf",
    "Bright Cluster Manager",
    "Parrot Security OS",
    "Pentoo",
    "SystemRescue",
    "Rescatux",
    "GParted Live",
    "Clonezilla Live",
    "Rescuezilla",
    "Finnix",
    "BlackArch",
    "Tails OS",
    "Kodachi",
    "BackBox",
    "GitHub",
    "Git",
    "GitLab",
    "Prometheus",
    "Grafana",
    "Elasticsearch",
    "Kibana",
    "Splunk",
    "Datadog",
    "New Relic",
    "Tableau",
    "Power BI",
    "Looker",
    "Jira",
    "Confluence",
    "Slack",
    "Zoom",
    "Microsoft Teams",
    "Salesforce",
    "SAP",
    "Oracle",
    "IBM",
    "Cisco",
    "Palo Alto Networks",
    "CrowdStrike",
    "SentinelOne",
    "Fortinet",
    "Check Point",
    "Trend Micro",
    "McAfee",
    "Norton",
    "Bitdefender",
    "Kaspersky",
    "ESET",
    "Sophos"
]

RANDOMIZE_CATEGORY = False
CURRENT_CATEGORY = random.choice(NEWS_CATEGORIES) if RANDOMIZE_CATEGORY else "technology"
SLIDE_DURATION = None  # Set to None for auto-sync with audio length, or a fixed number of seconds
SIZE_PORTRAIT = (1080, 1920)
SIZE_LANDSCAPE = (1920, 1080)
VIDEO_SIZE = SIZE_PORTRAIT
FONT_SIZE = 50
# LLM
#LLM_MODEL = "gemma4:31b"
LLM_MODEL = "llama3:latest"
LLM_URL = "http://127.0.0.1:11434/api/generate" 

# 🎙️ TTS CONFIGURATION
# Options: "edge" (free), "openai" (paid), "eleven" (paid/premium), "kokoro" (local/high-quality), "piper" (local/fast)
TTS_PROVIDER = "edge" 
RANDOMIZE_VOICE = True 

# If RANDOMIZE_VOICE is True and this list is NOT empty, it will pick one of these regardless of TTS_PROVIDER
RANDOM_VOICE_POOL = [
    "am_adam",                # Kokoro
    "en-US-AndrewNeural",      # Edge
    "bf_emma",                # Kokoro
    "en_US-lessac-high",        # Piper
    "en_US-ryan-high"           # Piper
]


# Professional Voice Recommendations:
# Piper Voices:
# en_US-amy-low ⭐ (lightweight, fast)
# en_US-amy-medium ⭐ (balanced quality)
# en_US-amy-high 🔥 (best quality, heavier)
# en_US-lessac-low
# en_US-lessac-medium
# en_US-lessac-high 🔥 (very natural)
# en_US-ryan-low
# en_US-ryan-medium
# en_US-ryan-high (Deep Male)
TTS_VOICE_PIPER = "en_US-lessac-medium"

# Kokoro: "af_heart" (Human/Warm), "af_bella" (Clear/Narrator), "am_adam" (Deep/Male)
TTS_VOICE_KOKORO = "af_heart"

# Edge TTS (Microsoft Neural): "en-US-AvaNeural" (Female/Pro), "en-US-AndrewNeural" (Male/Pro), "en-US-EmmaNeural", "en-US-BrianNeural"
TTS_VOICE_EDGE = "en-US-AvaNeural"

# 📱 FACEBOOK PAGE CONFIGURATION
UPLOAD_TO_FACEBOOK = True
FB_PAGE_ID = "111235544540553"
FB_PAGE_ACCESS_TOKEN = "EAAXQ6OrYrLMBRH57jWl14k4WHLBZAf2fZBDRmj4TzrlitZBnGrEgZBjuQZBvE6Ani0nzvSiwkDORpTTt6SAsBfZABvB2rLN5WXBhnthDYRhpt72TOBHmamxn1xqWk4O3vkrX88EdrqalxBZCDY5UE8cW4mu1rVvgtnJD3DC2fwej92PXmeRh3CBBlo52DLed7kBzqtqTGZCj9EOJql5zQ0ZBu"


# 📅 SCHEDULING
# Scheduling is dynamically calculated based on the Tech Niche Golden Strategy.
# See modules/schedule.py for details on timing rules.

# 📅 SUNDAY DIGEST SCHEDULE
# If the number of available tech news articles exceeds this threshold,
# the video will be scheduled for the next Sunday instead of the regular daily slot.
# This creates a special weekly "Tech Digest" drop for high-volume news weeks.
SUNDAY_DIGEST_THRESHOLD = 20          # Minimum articles to trigger Sunday scheduling
SUNDAY_DIGEST_TIME = (20, 30)         # Sunday upload slot: 8:30 PM
