import random
NEWS_API_KEY = "e7ebf6d7eecf479e95dcc55b4b5c812b"
NUM_ARTICLES = 10
DEDUPLICATE_NEWS = True 

# 📰 NEWS VARIETY
# Categories: technology, business, entertainment, general, health, science, sports
#NEWS_CATEGORIES = [
#    "NVIDIA GPU", "Intel CPU", "AMD Ryzen", "computer gaming news",
#    "information technology", "cloud computing", "AWS Azure Google Cloud",
#    "cybersecurity", "software development", "programming news",
#    "linux open source", "gadgets", "smartphones", "quantum computing",
#    "robotics", "automation", "server hardware", "networking IT"
#]
NEWS_CATEGORIES = [
    "Artificial Intelligence",
    "Machine Learning",
    "Generative AI",
    "OpenAI",
    "ChatGPT",
    "LLM Models",
    "AI Automation",
    "AI Startups",
    "AI Coding Tools",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "AI Agents",
    "Neural Networks",
    "Reinforcement Learning",
    "Federated Learning",
    "Transfer Learning",
    "Multimodal AI",
    "Diffusion Models",
    "Transformer Architecture",
    "Claude AI",
    "Gemini AI",
    "Mistral AI",
    "LLaMA",
    "AI Ethics",
    "AI Safety",
    "AI Regulation",
    "AI Hardware",
    "Edge AI",
    "TinyML",
    "Ollama",
    "OpenWebUI",
    "ComfyUI",
    "Stable Diffusion",
    "Flux AI",
    "NVIDIA GPU",
    "Intel CPU",
    "AMD Ryzen",
    "ARM Processors",
    "RISC-V",
    "TSMC",
    "Qualcomm",
    "Apple Silicon",
    "Semiconductor Industry",
    "Chip Manufacturing",
    "Cloud Computing",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "DevOps",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Ansible",
    "OpenStack",
    "VMware",
    "Cybersecurity",
    "Ethical Hacking",
    "Ransomware",
    "Malware Analysis",
    "Data Breaches",
    "Zero Trust Architecture",
    "SOC Security",
    "Network Security",
    "Penetration Testing",
    "Digital Forensics",
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Kotlin",
    "Swift",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Linux",
    "Ubuntu",
    "Debian",
    "Arch Linux",
    "Fedora",
    "Kali Linux",
    "Red Hat",
    "Open Source Software",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Apache Kafka",
    "Apache Hadoop",
    "Apache Spark",
    "Big Data",
    "Data Engineering",
    "Business Intelligence",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Web3",
    "NFT",
    "DeFi",
    "Quantum Computing",
    "Robotics",
    "Humanoid Robots",
    "Space Technology",
    "NASA",
    "ISRO",
    "SpaceX",
    "Starlink",
    "5G Technology",
    "6G Research",
    "Virtual Reality",
    "Augmented Reality",
    "Mixed Reality",
    "Metaverse",
    "Electric Vehicles",
    "Battery Technology",
    "Autonomous Vehicles",
    "Drone Technology",
    "Technology Startups",
    "Venture Capital",
    "IPO Technology",
    "Silicon Valley",
    "Big Tech Companies",
    "Technology Business News",
    "NVIDIA GPU",
    "Intel CPU",
    "AMD Ryzen",
    "ARM Processors",
    "RISC-V",
    "TSMC",
    "Qualcomm",
    "Apple Silicon",
    "Semiconductor Industry",
    "Chip Manufacturing",
    "Cloud Computing",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "DevOps",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Ansible",
    "OpenStack",
    "VMware",
    "Cybersecurity",
    "Ethical Hacking",
    "Ransomware",
    "Malware Analysis",
    "Data Breaches",
    "Zero Trust Architecture",
    "SOC Security",
    "Network Security",
    "Penetration Testing",
    "Digital Forensics",
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Kotlin",
    "Swift",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Linux",
    "Ubuntu",
    "Debian",
    "Arch Linux",
    "Fedora",
    "Kali Linux",
    "Red Hat",
    "Open Source Software",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Apache Kafka",
    "Apache Hadoop",
    "Apache Spark",
    "Big Data",
    "Data Engineering",
    "Business Intelligence",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Web3",
    "NFT",
    "DeFi",
    "Quantum Computing",
    "Robotics",
    "Humanoid Robots",
    "Space Technology",
    "NASA",
    "ISRO",
    "SpaceX",
    "Starlink",
    "5G Technology",
    "6G Research",
    "Virtual Reality",
    "Augmented Reality",
    "Mixed Reality",
    "Metaverse",
    "Electric Vehicles",
    "Battery Technology",
    "Autonomous Vehicles",
    "Drone Technology",
    "Technology Startups",
    "Venture Capital",
    "IPO Technology",
    "Silicon Valley",
    "Big Tech Companies",
    "Technology Business News",
    " Artificial Intelligence",
    "Machine Learning",
    "Generative AI",
    "OpenAI",
    "ChatGPT",
    "LLM Models",
    "AI Automation",
    "AI Startups",
    "AI Coding Tools",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "AI Agents",
    "Neural Networks",
    "Reinforcement Learning",
    "Federated Learning",
    "Transfer Learning",
    "Multimodal AI",
    "Diffusion Models",
    "Transformer Architecture",
    "Claude AI",
    "Gemini AI",
    "Mistral AI",
    "LLaMA",
    "AI Ethics",
    "AI Safety",
    "AI Regulation",
    "AI Hardware",
    "Edge AI",
    "TinyML",
    "Ollama",
    "OpenWebUI",
    "ComfyUI",
    "Stable Diffusion",
    "Flux AI",
    "NVIDIA GPU",
    "Intel CPU",
    "AMD Ryzen",
    "ARM Processors",
    "RISC-V",
    "TSMC",
    "Qualcomm",
    "Apple Silicon",
    "Semiconductor Industry",
    "Chip Manufacturing",
    "Cloud Computing",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "DevOps",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Ansible",
    "OpenStack",
    "VMware",
    "Cybersecurity",
    "Ethical Hacking",
    "Ransomware",
    "Malware Analysis",
    "Data Breaches",
    "Zero Trust Architecture",
    "SOC Security",
    "Network Security",
    "Penetration Testing",
    "Digital Forensics",
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Kotlin",
    "Swift",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Linux",
    "Ubuntu",
    "Debian",
    "Arch Linux",
    "Fedora",
    "Kali Linux",
    "Red Hat",
    "Open Source Software",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Apache Kafka",
    "Apache Hadoop",
    "Apache Spark",
    "Big Data",
    "Data Engineering",
    "Business Intelligence",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Web3",
    "NFT",
    "DeFi",
    "Quantum Computing",
    "Robotics",
    "Humanoid Robots",
    "Space Technology",
    "NASA",
    "ISRO",
    "SpaceX",
    "Starlink",
    "5G Technology",
    "6G Research",
    "Virtual Reality",
    "Augmented Reality",
    "Mixed Reality",
    "Metaverse",
    "Electric Vehicles",
    "Battery Technology",
    "Autonomous Vehicles",
    "Drone Technology",
    "Technology Startups",
    "Venture Capital",
    "IPO Technology",
    "Silicon Valley",
    "Big Tech Companies",
    "Technology Business News"
]

RANDOMIZE_CATEGORY = False
CURRENT_CATEGORY = random.choice(NEWS_CATEGORIES) if RANDOMIZE_CATEGORY else "technology"
SLIDE_DURATION = None  # Set to None for auto-sync with audio length, or a fixed number of seconds
SIZE_PORTRAIT = (1080, 1920)
SIZE_LANDSCAPE = (1920, 1080)
VIDEO_SIZE = SIZE_PORTRAIT
FONT_SIZE = 50
# LLM
#LLM_MODEL = "gemma4:31b"
LLM_MODEL = "qwen3-coder:480b-cloud"
LLM_URL = "http://127.0.0.1:11434/api/generate" 

# 🎙️ TTS CONFIGURATION
# Options: "edge" (free), "openai" (paid), "eleven" (paid/premium), "kokoro" (local/high-quality), "piper" (local/fast)
TTS_PROVIDER = "edge" 
RANDOMIZE_VOICE = True 

# If RANDOMIZE_VOICE is True and this list is NOT empty, it will pick one of these regardless of TTS_PROVIDER
RANDOM_VOICE_POOL = [
    "am_adam",                # Kokoro
    "en-US-AndrewNeural",      # Edge
    "bf_emma",                # Kokoro
    "en_US-lessac-high",        # Piper
    "en_US-ryan-high"           # Piper
]


# Professional Voice Recommendations:
# Piper Voices:
# en_US-amy-low ⭐ (lightweight, fast)
# en_US-amy-medium ⭐ (balanced quality)
# en_US-amy-high 🔥 (best quality, heavier)
# en_US-lessac-low
# en_US-lessac-medium
# en_US-lessac-high 🔥 (very natural)
# en_US-ryan-low
# en_US-ryan-medium
# en_US-ryan-high (Deep Male)
TTS_VOICE_PIPER = "en_US-lessac-medium"

# Kokoro: "af_heart" (Human/Warm), "af_bella" (Clear/Narrator), "am_adam" (Deep/Male)
TTS_VOICE_KOKORO = "af_heart"

# Edge TTS (Microsoft Neural): "en-US-AvaNeural" (Female/Pro), "en-US-AndrewNeural" (Male/Pro), "en-US-EmmaNeural", "en-US-BrianNeural"
TTS_VOICE_EDGE = "en-US-AvaNeural"

# 📱 FACEBOOK PAGE CONFIGURATION
UPLOAD_TO_FACEBOOK = True
FB_PAGE_ID = "111235544540553"
FB_PAGE_ACCESS_TOKEN = "EAAXQ6OrYrLMBRH57jWl14k4WHLBZAf2fZBDRmj4TzrlitZBnGrEgZBjuQZBvE6Ani0nzvSiwkDORpTTt6SAsBfZABvB2rLN5WXBhnthDYRhpt72TOBHmamxn1xqWk4O3vkrX88EdrqalxBZCDY5UE8cW4mu1rVvgtnJD3DC2fwej92PXmeRh3CBBlo52DLed7kBzqtqTGZCj9EOJql5zQ0ZBu"


# 📅 SCHEDULING
# Scheduling is dynamically calculated based on the Tech Niche Golden Strategy.
# See modules/schedule.py for details on timing rules.
